---
after_script:
- rake travis:after -t
before_script:
- gem install hoe-travis --no-rdoc --no-ri
- rake travis:before -t
language: ruby
notifications:
  email:
  - drbrain@segment7.net
rvm:
- 1.9.3
- 2.0.0
- 2.1.10
- 2.2.7
- 2.3.4
- 2.4.1
script: rake travis
